### ISSUE TITLE
Dépendance manquante

### ISSUE THREAD

**Issue by Chimrod** [Sorunome/reuben3-meta#1]
Le projet refuse de compiler à cause de la dépendance manquante RTCZero.

reuben3.ino:2:21: fatal error: RTCZero.h: No such file or directory

#include <RTCZero.h>
                     ^
compilation terminated.`

Quelle est la librairie à installer dans l'environnement Arduino ?

**Comment by Sorunome** [comment]
You have to install the RTCZero library via the arduino library manager

Am 2. Juni 2018 17:03:59 MESZ schrieb Chimrod <notifications@github.com>:

**Comment by Chimrod** [comment]
Thanks !

Can you just provide a readme in the project in order to explain required depencies ?

By the way, thanks a lot for the game ! You did a very good stuff
